---
.travis.yml:
  includes:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test FUTURE_PARSER=yes
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test FUTURE_PARSER=yes
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  allow_failures:
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
Gemfile:
  required:
    ':test':
      - gem: metadata-json-lint
      - gem: puppet-blacksmith
        git: https://github.com/voxpupuli/puppet-blacksmith.git
      - gem: puppet-lint
        git: https://github.com/rodjek/puppet-lint.git
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-version_comparison-check
      - gem: puppetlabs_spec_helper
      - gem: rake
      - gem: rspec
      - gem: rspec-puppet
        git: https://github.com/rodjek/rspec-puppet.git
      - gem: rspec-puppet-facts
      - gem: rspec-puppet-utils
      - gem: rubocop
        version: '~> 0.38'
    ':development':
      - gem: guard-rake
      - gem: travis
      - gem: travis-lint
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
        require: false
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_140chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
...

# vim: syntax=yaml
